// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/control': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/control/index.get').default>>>>
    }
    '/api/events/trip': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/events/trip.post').default>>>>
    }
    '/api/feed': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/feed.get').default>>>>
    }
    '/api/feed/follows': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/feed/follows.get').default>>>>
    }
    '/api/feed/follows/:uid': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/feed/follows/[uid].delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/feed/follows/[uid].post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/health.get').default>>>>
    }
    '/api/tasks/newsletter': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/tasks/newsletter.post').default>>>>
    }
  }
}
export {}