// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/rate-cards/:plan': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/admin/rate-cards/[plan].put').default>>>>
    }
    '/api/admin/rate-cards': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/admin/rate-cards/index.get').default>>>>
    }
    '/api/admin/rate-cards/overrides/:tenantId': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/admin/rate-cards/overrides/[tenantId].put').default>>>>
    }
    '/api/admin/usage/:tenantId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/admin/usage/[tenantId].get').default>>>>
    }
    '/api/admin/usage/bulk': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/admin/usage/bulk.get').default>>>>
    }
    '/api/control': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/control/index.get').default>>>>
    }
    '/api/events/usage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/events/usage.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/health.get').default>>>>
    }
    '/api/metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/metrics.get').default>>>>
    }
    '/api/ready': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/ready.get').default>>>>
    }
    '/api/tasks/period-rollup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/tasks/period-rollup.post').default>>>>
    }
    '/api/tasks/seat-snapshot': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/tasks/seat-snapshot.post').default>>>>
    }
    '/api/usage/current': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/usage/current.get').default>>>>
    }
  }
}
export {}