// Generated by nitro

// App Config
import type { Defu } from 'defu'



type UserAppConfig = Defu<{}, []>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}
  interface NitroRuntimeConfig {
   serviceName: string,

   services: {
      user: string,

      trip: string,

      destination: string,

      social: string,

      travelInfo: string,
   },
  }
}
export {}