// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/[...]').default>>>>
    }
    '/healthz': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/healthz.get').default>>>>
    }
    '/metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/metrics.get').default>>>>
    }
    '/tasks/flush-usage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/tasks/flush-usage.post').default>>>>
    }
  }
}
export {}