// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/alerts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/alerts.get').default>>>>
    }
    '/api/control/:worker/pause': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/control/[worker]/pause.post').default>>>>
    }
    '/api/control/:worker/resume': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/control/[worker]/resume.post').default>>>>
    }
    '/api/control': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/control/index.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/health.get').default>>>>
    }
    '/api/tasks/poll-warnings': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/tasks/poll-warnings.post').default>>>>
    }
    '/api/tasks/poll-weather': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/tasks/poll-weather.post').default>>>>
    }
    '/api/tasks/seed-warnings': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/tasks/seed-warnings.post').default>>>>
    }
  }
}
export {}