"""Signed-in user — exercises trip CRUD, likes, reviews."""
from __future__ import annotations

import json
import os
import random
import threading
from datetime import date, timedelta
from pathlib import Path

from locust import HttpUser, between, task

from auth import FirebaseSession, sign_in

ROOT = Path(__file__).resolve().parent.parent
SEEDED_FILE = ROOT / "seeded_users.json"

_account_lock = threading.Lock()
_account_cursor = 0
_accounts: list[dict] = []


def _load_accounts() -> list[dict]:
    global _accounts
    if _accounts:
        return _accounts
    if not SEEDED_FILE.exists():
        raise RuntimeError(
            f"{SEEDED_FILE} missing — run `python seed_users.py` first."
        )
    _accounts = json.loads(SEEDED_FILE.read_text())
    if not _accounts:
        raise RuntimeError("seeded_users.json is empty — re-run seeder with TEST_USER_COUNT > 0.")
    return _accounts


def _next_account() -> dict:
    """Round-robin account assignment so concurrent VUs don't all sign in as user 0."""
    global _account_cursor
    accounts = _load_accounts()
    with _account_lock:
        acc = accounts[_account_cursor % len(accounts)]
        _account_cursor += 1
    return acc


def _trip_payload() -> dict:
    today = date.today()
    start = today + timedelta(days=random.randint(7, 365))
    cities = ["Paris", "Rome", "Berlin", "Tokyo", "Lisbon", "Oslo", "Athens"]
    return {
        "title": f"Load Test Trip {random.randint(1000, 9999)}",
        "destination": random.choice(cities),
        "start_date": start.isoformat(),
        "short_description": "Synthetic trip generated by Locust load test.",
        "detail_description": "Created by automated load test. Safe to delete.",
    }


def _location_payload() -> dict:
    today = date.today()
    d_from = today + timedelta(days=random.randint(7, 30))
    d_to = d_from + timedelta(days=random.randint(1, 5))
    return {
        "name": f"Stop {random.randint(100, 999)}",
        "description": "Generated location.",
        "image_url": "",
        "date_from": d_from.isoformat(),
        "date_to": d_to.isoformat(),
    }


class AuthedUser(HttpUser):
    """Signed-in user. weights write paths heavier than reads."""

    weight = 1
    wait_time = between(2, 5)

    session: FirebaseSession | None = None
    created_trip_ids: list[int]
    public_trip_ids: list[dict]  # [{id, user_uid}, ...] — for picking review targets

    def on_start(self) -> None:
        api_key = os.environ.get("FIREBASE_API_KEY", "").strip()
        if not api_key:
            raise RuntimeError("FIREBASE_API_KEY missing in env. See tests/load/.env.example.")

        password = os.environ.get("TEST_USER_PASSWORD", "LoadTest!2026")
        account = _next_account()

        self.session = sign_in(account["email"], password, api_key)
        self.client.headers["Authorization"] = self.session.authorization_header()
        self.created_trip_ids = []
        self.public_trip_ids = []

        # Upsert into Postgres users table (POST /api/users requires auth, body name optional)
        self.client.post(
            "/api/users",
            json={"name": f"LoadTester {account['uid'][:6]}"},
            name="/api/users (upsert self)",
        )

        # Prime list of other users' trips for review tasks
        with self.client.get("/api/trips/all", name="/api/trips/all (prime)", catch_response=True) as r:
            if r.ok:
                try:
                    self.public_trip_ids = [
                        {"id": t["id"], "user_uid": t.get("user_uid")}
                        for t in r.json()
                        if "id" in t
                    ]
                except (ValueError, TypeError):
                    pass

    def _refresh_if_needed(self) -> None:
        if self.session and self.session.expired:
            try:
                self.session.refresh()
                self.client.headers["Authorization"] = self.session.authorization_header()
            except Exception:
                pass  # next request will 401, Locust counts as failure

    @task(4)
    def dashboard(self) -> None:
        self._refresh_if_needed()
        self.client.get("/api/users/me", name="/api/users/me")
        self.client.get("/api/trips", name="/api/trips (mine)")

    @task(2)
    def create_trip_with_location(self) -> None:
        self._refresh_if_needed()
        with self.client.post(
            "/api/trips",
            json=_trip_payload(),
            name="/api/trips (create)",
            catch_response=True,
        ) as r:
            if not r.ok:
                return
            try:
                trip = r.json()
                trip_id = trip["id"]
            except (ValueError, KeyError):
                r.failure("trip create returned no id")
                return
            self.created_trip_ids.append(trip_id)

        self.client.post(
            f"/api/locations/trip/{trip_id}",
            json=_location_payload(),
            name="/api/locations/trip/[id] (create)",
        )
        self.client.get(f"/api/trips/{trip_id}", name="/api/trips/[id]")

    @task(2)
    def like_trip(self) -> None:
        if not self.public_trip_ids:
            return
        self._refresh_if_needed()
        target = random.choice(self.public_trip_ids)
        self.client.post(
            f"/api/likes/trip/{target['id']}",
            json={"comment": random.choice(["nice!", "love it", "going there", ""])},
            name="/api/likes/trip/[id] (POST)",
        )

    @task(1)
    def update_trip(self) -> None:
        if not self.created_trip_ids:
            return
        self._refresh_if_needed()
        trip_id = random.choice(self.created_trip_ids)
        payload = _trip_payload()
        self.client.put(
            f"/api/trips/{trip_id}",
            json=payload,
            name="/api/trips/[id] (PUT)",
        )

    @task(1)
    def review_others_trip(self) -> None:
        if not self.session or not self.public_trip_ids:
            return
        # Cannot review own trip → 403. Filter.
        candidates = [t for t in self.public_trip_ids if t.get("user_uid") != self.session.uid]
        if not candidates:
            return
        self._refresh_if_needed()
        target = random.choice(candidates)
        self.client.post(
            f"/api/reviews/trip/{target['id']}",
            json={"stars": random.randint(1, 5), "comment": "Generated review."},
            name="/api/reviews/trip/[id] (POST)",
        )

    @task(1)
    def delete_own_trip(self) -> None:
        if not self.created_trip_ids:
            return
        self._refresh_if_needed()
        trip_id = self.created_trip_ids.pop(0)
        self.client.delete(f"/api/trips/{trip_id}", name="/api/trips/[id] (DELETE)")
