// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/control': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/control/index.get').default>>>>
    }
    '/api/events/alert': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/events/alert.post').default>>>>
    }
    '/api/events/newsletter': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/events/newsletter.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/health.get').default>>>>
    }
  }
}
export {}