// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/buses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/buses/index.get').default>>>>
    }
    '/api/flights': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/flights/index.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/health.get').default>>>>
    }
    '/api/hotels': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/hotels/index.get').default>>>>
    }
    '/api/internal/active-trips': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/internal/active-trips.get').default>>>>
    }
    '/api/internal/destination-stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/internal/destination-stats.get').default>>>>
    }
    '/api/likes/trip/:tripId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/likes/trip/[tripId].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/likes/trip/[tripId].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/likes/trip/[tripId].post').default>>>>
    }
    '/api/locations/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/locations/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/locations/[id].put').default>>>>
    }
    '/api/locations/trip/:tripId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/locations/trip/[tripId].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/locations/trip/[tripId].post').default>>>>
    }
    '/api/reviews/trip/:tripId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/reviews/trip/[tripId].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/reviews/trip/[tripId].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/reviews/trip/[tripId].post').default>>>>
    }
    '/api/travel-plans/:tripId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/travel-plans/[tripId].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/travel-plans/[tripId].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/travel-plans/[tripId].post').default>>>>
    }
    '/api/trips/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/trips/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/trips/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/trips/[id].put').default>>>>
    }
    '/api/trips/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/trips/all.get').default>>>>
    }
    '/api/trips': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/trips/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/trips/index.post').default>>>>
    }
  }
}
export {}