// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/health.get').default>>>>
    }
    '/api/internal/tenants/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/internal/tenants/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/internal/tenants/[id].put').default>>>>
    }
    '/api/internal/users/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/internal/users/[id].patch').default>>>>
    }
    '/api/tenants/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/tenants/[id].get').default>>>>
    }
    '/api/users/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/users/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/users/[id].patch').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/users/[id].put').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/users/index.post').default>>>>
    }
    '/api/users/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/users/me.get').default>>>>
    }
  }
}
export {}