// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/b2b/destinations/:id/travelers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/b2b/destinations/[id]/travelers.get').default>>>>
    }
    '/api/destinations/:id/routes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/destinations/[id]/routes.get').default>>>>
    }
    '/api/destinations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/destinations/index.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/health.get').default>>>>
    }
    '/api/plan-refs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/plan-refs.get').default>>>>
    }
  }
}
export {}