"""Seed N trips per Firebase test user — gives Browsing scenario data to read.

Run after `seed_users.py`. Reads seeded_users.json, signs each user in via the
Firebase REST API, then POSTs trips to /api/trips on the chosen target.

Usage:
    python seed_trips.py                                    # 3 trips/user vs http://localhost:3000
    python seed_trips.py --count 5 --target https://...     # 5 trips/user vs prod
    python seed_trips.py --cleanup                          # delete every "Seed Trip " row this user owns

Idempotent: trips with title prefix "Seed Trip " are pruned per-user before re-seeding,
so re-running yields the configured count exactly.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import sys
from datetime import date, timedelta
from pathlib import Path

import requests
from dotenv import load_dotenv

ROOT = Path(__file__).parent
load_dotenv(ROOT / ".env")
sys.path.insert(0, str(ROOT))

from auth import sign_in  # noqa: E402

SEEDED_FILE = ROOT / "seeded_users.json"
TRIP_TITLE_PREFIX = "Seed Trip "

CITIES = [
    "Paris", "Rome", "Berlin", "Tokyo", "Lisbon", "Oslo", "Athens",
    "Barcelona", "Amsterdam", "Prague", "Vienna", "Budapest", "Reykjavik",
]
SHORT_DESCRIPTIONS = [
    "Sun, food, and a small carry-on bag.",
    "Off-season escape to a quiet coast.",
    "Family roadtrip with too many photos.",
    "Solo hike + cafe sit-downs.",
    "Long weekend museum crawl.",
]


def load_users() -> list[dict]:
    if not SEEDED_FILE.exists():
        sys.exit(f"{SEEDED_FILE} missing — run seed_users.py first.")
    return json.loads(SEEDED_FILE.read_text())


def trip_payload(idx: int) -> dict:
    today = date.today()
    start = today + timedelta(days=random.randint(7, 365))
    return {
        "title": f"{TRIP_TITLE_PREFIX}{idx:03d} — {random.choice(CITIES)}",
        "destination": random.choice(CITIES),
        "start_date": start.isoformat(),
        "short_description": random.choice(SHORT_DESCRIPTIONS),
        "detail_description": "Generated by seed_trips.py — safe to delete.",
    }


def auth_headers(api_key: str, email: str, password: str) -> dict:
    session = sign_in(email, password, api_key)
    return {"Authorization": session.authorization_header()}


def list_my_trips(target: str, headers: dict) -> list[dict]:
    r = requests.get(f"{target}/api/trips", headers=headers, timeout=15)
    if not r.ok:
        return []
    try:
        return r.json()
    except ValueError:
        return []


def upsert_user(target: str, headers: dict, name: str) -> None:
    requests.post(
        f"{target}/api/users",
        headers={**headers, "Content-Type": "application/json"},
        json={"name": name},
        timeout=15,
    )


def delete_seed_trips(target: str, headers: dict) -> int:
    deleted = 0
    for trip in list_my_trips(target, headers):
        if str(trip.get("title", "")).startswith(TRIP_TITLE_PREFIX):
            r = requests.delete(f"{target}/api/trips/{trip['id']}", headers=headers, timeout=15)
            if r.ok:
                deleted += 1
    return deleted


def seed(target: str, count: int) -> None:
    api_key = os.environ.get("FIREBASE_API_KEY", "").strip()
    if not api_key:
        sys.exit("FIREBASE_API_KEY missing in .env")
    password = os.environ.get("TEST_USER_PASSWORD", "LoadTest!2026")

    users = load_users()
    total_created = 0
    for i, account in enumerate(users):
        try:
            headers = auth_headers(api_key, account["email"], password)
        except Exception as e:
            print(f"[!] sign-in failed for {account['email']}: {e}")
            continue

        upsert_user(target, headers, f"LoadTester {account['uid'][:6]}")

        # Wipe previous seed trips → idempotent
        delete_seed_trips(target, headers)

        for n in range(count):
            payload = trip_payload(n)
            r = requests.post(
                f"{target}/api/trips",
                headers={**headers, "Content-Type": "application/json"},
                json=payload,
                timeout=15,
            )
            if r.ok:
                total_created += 1
            else:
                print(f"[!] trip create failed for {account['email']}: {r.status_code} {r.text[:120]}")

        print(f"[+] {account['email']} → {count} trips")

    print(f"\nCreated {total_created} trips across {len(users)} users.")


def cleanup(target: str) -> None:
    api_key = os.environ.get("FIREBASE_API_KEY", "").strip()
    if not api_key:
        sys.exit("FIREBASE_API_KEY missing in .env")
    password = os.environ.get("TEST_USER_PASSWORD", "LoadTest!2026")

    users = load_users()
    total_deleted = 0
    for account in users:
        try:
            headers = auth_headers(api_key, account["email"], password)
        except Exception as e:
            print(f"[!] sign-in failed for {account['email']}: {e}")
            continue
        n = delete_seed_trips(target, headers)
        total_deleted += n
        print(f"[-] {account['email']} → deleted {n}")

    print(f"\nDeleted {total_deleted} seed trips.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", default=os.environ.get("TARGET_LOCAL", "http://localhost:3000"))
    parser.add_argument("--count", type=int, default=3, help="Trips per user")
    parser.add_argument("--cleanup", action="store_true")
    args = parser.parse_args()

    if args.cleanup:
        cleanup(args.target)
    else:
        seed(args.target, args.count)
