// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/health.get').default>>>>
    }
    '/api/internal/deprovision-tenant': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/internal/deprovision-tenant.post').default>>>>
    }
    '/api/internal/provision-tenant': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/internal/provision-tenant.post').default>>>>
    }
    '/api/ready': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/ready.get').default>>>>
    }
  }
}
export {}